_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "outputs/output_diffdet_quadrant/model_final.pth"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 4  # 
DATASETS:
  TRAIN: ("dentex_quadrant_train",)
  TEST:  ("dentex_quadrant_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 40000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:  # LVIS
  EVAL_PERIOD: 1000  # disable eval during train since long time
